// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZN2xIFo8aesSKNDuVyY6yVBAgZPsjQzw',
    appId: '1:127471265186:web:b26d64c3e92936faa6fefb',
    messagingSenderId: '127471265186',
    projectId: 'taskease-34b09',
    authDomain: 'taskease-34b09.firebaseapp.com',
    storageBucket: 'taskease-34b09.firebasestorage.app',
    measurementId: 'G-M7TD0WR1LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw515O6iK6ZxzD1LWvnZryIjOhm7ZSUYc',
    appId: '1:127471265186:android:19a08ed05eb5d5f0a6fefb',
    messagingSenderId: '127471265186',
    projectId: 'taskease-34b09',
    storageBucket: 'taskease-34b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpRN-j0Ajsk-RPi_08BwKBCU8LJrhqV8Q',
    appId: '1:127471265186:ios:2bff43a538bad69aa6fefb',
    messagingSenderId: '127471265186',
    projectId: 'taskease-34b09',
    storageBucket: 'taskease-34b09.firebasestorage.app',
    iosBundleId: 'com.kenstarry.taskEase',
  );
}
